import type { LineDefinition } from './types';

/**
 * 화면에 표시할 PL 라인 정의 (순서 및 구조 고정)
 * CSV에 더 많은 계정이 있어도 화면에는 이 정의만 노출
 */
export const lineDefinitions: LineDefinition[] = [
  // 1) Tag매출
  {
    id: 'tag-sale',
    label: 'Tag매출',
    level: 0,
    isParent: true,
    isCalculated: false,
    defaultExpanded: false,
    level1: 'Tag매출',
    children: [
      {
        id: 'tag-sale-online-direct',
        label: '온라인 직영',
        level: 1,
        isParent: false,
        isCalculated: false,
        type: 'channelTagSale',
      },
      {
        id: 'tag-sale-online-dealer',
        label: '온라인 대리상',
        level: 1,
        isParent: false,
        isCalculated: false,
        type: 'channelTagSale',
      },
      {
        id: 'tag-sale-offline-direct',
        label: '오프라인 직영',
        level: 1,
        isParent: false,
        isCalculated: false,
        type: 'channelTagSale',
      },
      {
        id: 'tag-sale-offline-dealer',
        label: '오프라인 대리상',
        level: 1,
        isParent: false,
        isCalculated: false,
        type: 'channelTagSale',
      },
    ],
  },

  // 2) 실판(V+)
  {
    id: 'act-sale-vat-inc',
    label: '실판(V+)',
    level: 0,
    isParent: true,
    isCalculated: false,
    defaultExpanded: true,
    level1: '실판(V+)',
    children: [
      {
        id: 'act-sale-vat-inc-online-direct',
        label: '온라인 직영',
        level: 1,
        isParent: false,
        isCalculated: false,
        type: 'channelVatInc',
      },
      {
        id: 'act-sale-vat-inc-online-dealer',
        label: '온라인 대리상',
        level: 1,
        isParent: false,
        isCalculated: false,
        type: 'channelVatInc',
      },
      {
        id: 'act-sale-vat-inc-offline-direct',
        label: '오프라인 직영',
        level: 1,
        isParent: false,
        isCalculated: false,
        type: 'channelVatInc',
      },
      {
        id: 'act-sale-vat-inc-offline-dealer',
        label: '오프라인 대리상',
        level: 1,
        isParent: false,
        isCalculated: false,
        type: 'channelVatInc',
      },
    ],
  },

  // 3) 매출원가 합계 (부모행, 토글 가능)
  {
    id: 'cogs-sum',
    label: '매출원가 합계',
    level: 0,
    isParent: true,
    isCalculated: true,
    defaultExpanded: false,
    type: 'cogsSum',
    children: [
      {
        id: 'cogs',
        label: '매출원가',
        level: 1,
        isParent: true,
        isCalculated: false,
        defaultExpanded: false,
        level1: '매출원가',
        children: [
          {
            id: 'cogs-online-direct',
            label: '온라인 직영',
            level: 2,
            isParent: false,
            isCalculated: false,
            type: 'channelCogs',
          },
          {
            id: 'cogs-online-dealer',
            label: '온라인 대리상',
            level: 2,
            isParent: false,
            isCalculated: false,
            type: 'channelCogs',
          },
          {
            id: 'cogs-offline-direct',
            label: '오프라인 직영',
            level: 2,
            isParent: false,
            isCalculated: false,
            type: 'channelCogs',
          },
          {
            id: 'cogs-offline-dealer',
            label: '오프라인 대리상',
            level: 2,
            isParent: false,
            isCalculated: false,
            type: 'channelCogs',
          },
        ],
      },
      {
        id: 'eval-reversal',
        label: '평가감(환입)',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '평가감',
        level3: '평가감(환입)',
      },
      {
        id: 'eval-provision',
        label: '평가감(설정)',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '평가감',
        level3: '평가감(설정)',
      },
    ],
  },

  // 4) 매출총이익 (계산행)
  {
    id: 'gross-profit',
    label: '매출총이익',
    level: 0,
    isParent: false,
    isCalculated: true,
    type: 'grossProfit',
  },

  // 5) 직접비 합계 (부모행, 토글 가능)
  {
    id: 'direct-cost-sum',
    label: '직접비 합계',
    level: 0,
    isParent: true,
    isCalculated: true,
    defaultExpanded: false,
    type: 'directCostSum',
    costCategory: 'direct',
    children: [
      {
        id: 'direct-salary',
        label: '급여',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: '급여',
        costCategory: 'direct',
      },
      {
        id: 'direct-welfare',
        label: '복리후생비',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: '복리후생비',
        costCategory: 'direct',
      },
      {
        id: 'direct-platform-fee',
        label: '플랫폼수수료',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: '플랫폼수수료',
        costCategory: 'direct',
      },
      {
        id: 'direct-tp-fee',
        label: 'TP수수료',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: 'TP수수료',
        costCategory: 'direct',
      },
      {
        id: 'direct-ad',
        label: '직접광고비',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: '직접광고비',
        costCategory: 'direct',
      },
      {
        id: 'dealer-support',
        label: '대리상지원금',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: '대리상지원금',
        type: 'dealerSupport',
        costCategory: 'direct',
      },
      {
        id: 'direct-logistics',
        label: '물류비',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: '물류비',
        costCategory: 'direct',
      },
      {
        id: 'direct-rental',
        label: '매장임차료',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: '매장임차료',
        costCategory: 'direct',
      },
      {
        id: 'direct-depreciation',
        label: '감가상각비',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '직접비',
        level2: '감가상각비',
        costCategory: 'direct',
      },
      {
        id: 'direct-other',
        label: '기타',
        level: 1,
        isParent: true,
        isCalculated: true,
        defaultExpanded: false,
        level1: '직접비',
        level2: '기타',
        costCategory: 'direct',
        children: [
          {
            id: 'direct-other-display',
            label: '진열소모품',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '직접비',
            level2: '기타',
            level3: '진열소모품',
            costCategory: 'direct',
          },
          {
            id: 'direct-other-package',
            label: '포장비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '직접비',
            level2: '기타',
            level3: '포장비',
            costCategory: 'direct',
          },
          {
            id: 'direct-other-fee',
            label: '지급수수료',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '직접비',
            level2: '기타',
            level3: '지급수수료',
            costCategory: 'direct',
          },
          {
            id: 'direct-other-consumable',
            label: '기타소모품',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '직접비',
            level2: '기타',
            level3: '기타소모품',
            costCategory: 'direct',
          },
          {
            id: 'direct-other-comm',
            label: '통신비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '직접비',
            level2: '기타',
            level3: '통신비',
            costCategory: 'direct',
          },
          {
            id: 'direct-other-travel',
            label: '출장비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '직접비',
            level2: '기타',
            level3: '출장비',
            costCategory: 'direct',
          },
          {
            id: 'direct-other-entertainment',
            label: '접대비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '직접비',
            level2: '기타',
            level3: '접대비',
            costCategory: 'direct',
          },
          {
            id: 'direct-other-misc-fee',
            label: '기타지급수수료',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '직접비',
            level2: '기타',
            level3: '기타지급수수료',
            costCategory: 'direct',
          },
        ],
      },
    ],
  },

  // 6) 직접이익 (계산행)
  {
    id: 'direct-profit',
    label: '직접이익',
    level: 0,
    isParent: false,
    isCalculated: true,
    type: 'directProfit',
  },

  // 7) 영업비 합계 (부모행, 토글 가능)
  {
    id: 'opex-sum',
    label: '영업비 합계',
    level: 0,
    isParent: true,
    isCalculated: true,
    defaultExpanded: false,
    type: 'opexSum',
    costCategory: 'opex',
    children: [
      {
        id: 'opex-salary',
        label: '급여',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '영업비',
        level2: '급여',
        costCategory: 'opex',
      },
      {
        id: 'opex-welfare',
        label: '복리후생비',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '영업비',
        level2: '복리후생비',
        costCategory: 'opex',
      },
      {
        id: 'opex-ad',
        label: '광고비',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '영업비',
        level2: '광고비',
        costCategory: 'opex',
      },
      {
        id: 'opex-tradeshow',
        label: '수주회',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '영업비',
        level2: '수주회',
        costCategory: 'opex',
      },
      {
        id: 'opex-fee',
        label: '지급수수료',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '영업비',
        level2: '지급수수료',
        costCategory: 'opex',
      },
      {
        id: 'opex-rental',
        label: '임차료',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '영업비',
        level2: '임차료',
        costCategory: 'opex',
      },
      {
        id: 'opex-depreciation',
        label: '감가상각비',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '영업비',
        level2: '감가상각비',
        costCategory: 'opex',
      },
      {
        id: 'opex-tax',
        label: '세금과공과',
        level: 1,
        isParent: false,
        isCalculated: false,
        level1: '영업비',
        level2: '세금과공과',
        costCategory: 'opex',
      },
      {
        id: 'opex-other',
        label: '기타',
        level: 1,
        isParent: true,
        isCalculated: true,
        defaultExpanded: false,
        level1: '영업비',
        level2: '기타',
        costCategory: 'opex',
        children: [
          {
            id: 'opex-other-print',
            label: '도서인쇄비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '영업비',
            level2: '기타',
            level3: '도서인쇄비',
            costCategory: 'opex',
          },
          {
            id: 'opex-other-comm',
            label: '통신비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '영업비',
            level2: '기타',
            level3: '통신비',
            costCategory: 'opex',
          },
          {
            id: 'opex-other-direct-staff',
            label: '직영판매사원도급비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '영업비',
            level2: '기타',
            level3: '직영판매사원도급비',
            costCategory: 'opex',
          },
          {
            id: 'opex-other-travel',
            label: '국내출장비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '영업비',
            level2: '기타',
            level3: '국내출장비',
            costCategory: 'opex',
          },
          {
            id: 'opex-other-entertainment',
            label: '접대비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '영업비',
            level2: '기타',
            level3: '접대비',
            costCategory: 'opex',
          },
          {
            id: 'opex-other-consumable',
            label: '기타소모품',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '영업비',
            level2: '기타',
            level3: '기타소모품',
            costCategory: 'opex',
          },
          {
            id: 'opex-other-misc-fee',
            label: '기타지급수수료',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '영업비',
            level2: '기타',
            level3: '기타지급수수료',
            costCategory: 'opex',
          },
          {
            id: 'opex-other-vehicle',
            label: '차량유지비',
            level: 2,
            isParent: false,
            isCalculated: false,
            level1: '영업비',
            level2: '기타',
            level3: '차량유지비',
            costCategory: 'opex',
          },
        ],
      },
    ],
  },

  // 8) 영업이익 (계산행)
  {
    id: 'operating-profit',
    label: '영업이익',
    level: 0,
    isParent: false,
    isCalculated: true,
    type: 'operatingProfit',
  },
];

// 대리상지원금 계산에 사용되는 item (다른 라인 합산에서 제외)
export const dealerSupportItems = [
  'OUTSRC_PROC_CST',
  'SMPL_BUY_CST',
  'MILE_SALE_AMT',
];

// VAT 제외 실판 컬럼명
export const vatExcludedItem = 'VAT_EXC_ACT_SALE_AMT';

